import { BaseModel } from '../../_base/crud';

export class EmployeeModel  extends BaseModel {
	id: number;
	first_name: string;
    last_name: string;
    id_number: string; 
	gender: string;
    birthday: any;
    nationality: string;
    user_id: number; 
    home_phone_number: string;
    mobile_phone_number: string;
    personal_email: string;
    marital: string;
    skype_id: string;
    referal_name: string;
    country: string;
    state: string;
    home_address: string;
    deport_america: number;
    check_america: number;
    check_background: number;
    english_level: string;
    passport_path: any;
    passport_date:string;
    reference_path: any;
    reference_date:string;
    cv_path: any;
    cv_date:string;
    police_path: any;
    police_date:string;
	available_works: string;
    have_computer: number;
    have_monitor: number;
    have_headset: number;
    have_ethernet: number;
    visit: number;
    approve_date:string;
    created_at:string;
    created_date:string;
    photo:any;
    documents:any;
    status: string;
    errors:any;
    skills:any;
    photos:any;

	clear() {
		this.first_name = '';
		this.last_name = '';
		this.id_number = '';
		this.gender = '';
		this.birthday = new Date();
		this.nationality = '';
        this.user_id = null;
        this.home_phone_number = '';
        this.mobile_phone_number = '';
        this.personal_email = '';
        this.marital = '';
        this.skype_id = '';
        this.referal_name = '';
        this.country = '';
        this.state = '';
        this.home_address = '';
        this.deport_america = 0;
        this.check_america = 0;
        this.check_background = 0;
        this.english_level = 'Basic';
        this.passport_path = null;
        this.reference_path = null;
        this.cv_path = null;
        this.police_path = null;
        this.available_works = 'Less_20';
        this.have_computer = 0;
        this.have_monitor = 0;
        this.have_headset = 0;
        this.have_ethernet = 0;
        this.visit = 0;
        this.approve_date = '';
        this.status = '';
    }
}
